require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - app/rpc/definitions/**/*.rb
    - db/schema.rb
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
