require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - app/rpc/definitions/**/*.rb
    - db/schema.rb
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - app/rpc/*_controller.rb

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
