# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookmarks.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("bookmarks.proto", :syntax => :proto3) do
    add_message "rpc.Bookmark" do
      optional :id, :uint64, 1
      optional :bookmarked_url, :string, 2
      optional :canonical_url, :string, 3
      optional :archive_org_snapshot_url, :string, 4
      optional :initial_http_status_code, :string, 5
      optional :final_http_status_code, :string, 6
      optional :note, :string, 7
      optional :created_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "rpc.GetBookmarkRequest" do
      optional :id, :uint64, 1
    end
    add_message "rpc.ListBookmarksRequest" do
      optional :limit, :uint64, 1
      optional :offset, :uint64, 2
    end
  end
end

module Rpc
  Bookmark = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Bookmark").msgclass
  GetBookmarkRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetBookmarkRequest").msgclass
  ListBookmarksRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ListBookmarksRequest").msgclass
end
