# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bookmarks.proto for package 'rpc'

require 'grpc'
require 'bookmarks_pb'

module Rpc
  module Bookmarks
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Bookmarks'

      rpc :GetBookmark, GetBookmarkRequest, Bookmark
      rpc :ListBookmarks, ListBookmarksRequest, stream(Bookmark)
    end

    Stub = Service.rpc_stub_class
  end
end
